# 災害関連の施設の一覧表を作成する。

以下の神戸市のデータを組み合わせる。
- 避難所一覧
- 災害時こまらんトイレ整備ヶ所一覧
- 貯水機能のある災害時給水拠点一覧
- （福祉避難所一覧）←緯度、経度の記載がないのと、今回のデモでは重要度は低いので後回し。


カラム：
- kind: 施設種類
- name: 施設名
- latitude: 緯度
- longitude: 経度
- color: 地図上に表示する際の色

In [7]:
import pandas as pd
import json

In [4]:
%%bash
cd assets
ls

kobe_chuo_population.jpg
災害時こまらんトイレ整備箇所一覧.csv
神戸市避難所一覧.csv
貯水機能のある災害時給水拠点一覧_緯度経度あり.csv

In [6]:
df_evacuation = pd.read_csv('assets/神戸市避難所一覧.csv')
df_toile = pd.read_csv('assets/災害時こまらんトイレ整備箇所一覧.csv')
df_water = pd.read_csv('assets/貯水機能のある災害時給水拠点一覧_緯度経度あり.csv')

In [13]:
df_evacuation

,番号,区,緊急避難場所の利用,避難所の利用,名称,住所,電話番号,郵便番号,土砂災害,洪水,津波,備考,世界_10進_X,世界_10進_Y
0,1,東灘,○,○,東灘小学校,神戸市東灘区深江北町2-4-1,078-411-0556,658-0013,○,○,〇,NaN,135.294429,34.724816
1,2,東灘,○,○,本庄小学校,神戸市東灘区青木4-4-1,078-411-0339,658-0027,○,○,×,NaN,135.288700,34.721020
2,3,東灘,○,○,本庄中学校,神戸市東灘区青木4-4-2,078-411-2261,658-0027,○,○,×,NaN,135.287544,34.720461
3,4,東灘,○,○,東灘高校,神戸市東灘区深江浜町50,078-452-9600,658-0023,○,○,×,NaN,135.301049,34.709979
4,5,東灘,○,○,神戸大学海洋政策科学部,神戸市東灘区深江南町5-1-1,078-431-6200,658-0022,○,○,×,NaN,135.288358,34.718744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,332,西,○,○,玉津中学校,神戸市西区玉津町今津364,078-918-2266,651-2128,○,○,－,NaN,134.992486,34.678347
332,333,西,○,○,神出小学校,神戸市西区神出町田井444,078-965-0006,651-2313,○,○,－,NaN,134.987733,34.747371
333,334,西,○,○,神出中学校,神戸市西区神出町東1167,078-965-0025,651-2311,△,○,－,《土砂災害時》山腹崩壊に注意,134.996443,34.754814
334,335,西,○,○,岩岡小学校,神戸市西区岩岡町古郷267,078-967-0013,651-2404,○,○,－,NaN,134.944293,34.718229
335,336,西,○,○,岩岡中学校,神戸市西区岩岡町古郷249-1,078-967-0016,651-2404,○,○,－,NaN,134.943379,34.716282

In [29]:
columns = ['kind', 'name', 'latitude', 'longitude', 'color']
df_all = pd.DataFrame(columns=columns)
df_all

Empty DataFrame
Columns: [kind, name, latitude, longitude, color]
Index: []

In [33]:
# 避難所一覧データ
kind = '避難所'
for row in df_evacuation.iterrows():
    
    name = row[1]['名称']
    lng = row[1]['世界_10進_X']
    lat = row[1]['世界_10進_Y']
    
    df_one = pd.DataFrame(
        [[kind, name, lat, lng, '#ff00ff']],
        columns=columns
    )
    
    df_all = pd.concat([df_all, df_one], axis=0, ignore_index=True)
    

# 災害時こまらんトイレ整備ヶ所一覧データ
kind = '災害時こまらんトイレ'
for row in df_toile.iterrows():
    
    name = row[1]['学校名']
    lng = row[1]['経度']
    lat = row[1]['緯度']
    
    df_one = pd.DataFrame(
        [[kind, name, lat, lng, '#daa520']],
        columns=columns
    )
    
    df_all = pd.concat([df_all, df_one], axis=0, ignore_index=True)
    
    

# 貯水機能のある災害時給水拠点一覧
kind = '災害時給水拠点'
for row in df_water.iterrows():
    
    name = row[1]['施設名']
    lng = row[1]['経度']
    lat = row[1]['緯度']
    
    df_one = pd.DataFrame(
        [[kind, name, lat, lng, '#00bfff']],
        columns=columns
    )
    
    df_all = pd.concat([df_all, df_one], axis=0, ignore_index=True)

In [34]:
df_all

        kind         name   latitude   longitude    color
0        避難所        東灘小学校  34.724816  135.294429  #ff00ff
1        避難所        本庄小学校  34.721020  135.288700  #ff00ff
2        避難所        本庄中学校  34.720461  135.287544  #ff00ff
3        避難所         東灘高校  34.709979  135.301049  #ff00ff
4        避難所  神戸大学海洋政策科学部  34.718744  135.288358  #ff00ff
..       ...          ...        ...         ...      ...
907  災害時給水拠点      王子南給水拠点  34.706380  135.213937  #00bfff
908  災害時給水拠点      板宿中層配水池  34.662758  135.127867  #00bfff
909  災害時給水拠点  見津が丘特1高区配水池  34.736769  135.088266  #00bfff
910  災害時給水拠点      石屋川給水拠点  34.721290  135.248978  #00bfff
911  災害時給水拠点      奥平野給水拠点  34.694097  135.176262  #00bfff

[912 rows x 5 columns]

In [35]:
df_all.to_csv('df_disaster_related_site.csv',header=True, index=False)

In [8]:
import requests

url = "https://sheets.googleapis.com/v4/spreadsheets/1MwkW5QdNA27qt-CzQ1kpLIylzeCn0ojFPp3mvT238Q0/values/フォームの回答 1?key=AIzaSyBXzRVAv-WkZJspvuJuvU0XuSU6cJBP34Q"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

In [9]:
jsonData = json.loads(response.text)
jsonData

{'range': "'フォームの回答 1'!A1:V103",
 'majorDimension': 'ROWS',
 'values': [['タイムスタンプ',
   '性別',
   '会社から自宅までの距離',
   '家族構成について教えてください [幼児（男/女：0~3歳）]',
   '家族構成について教えてください [子供（男/女：4~18歳）]',
   '家族構成について教えてください [成人（男性）]',
   '家族構成について教えてください [成人（女性）]',
   '家族構成について教えてください [高齢者（男性：65歳以上）]',
   '家族構成について教えてください [高齢者（女性：65歳以上）]',
   '自宅の耐震・防火工事はしていますか？',
   '自宅にはどのくらいの備蓄がありますか？ [飲料水（1人分 3ℓ/日）]',
   '自宅にはどのくらいの備蓄がありますか？ [食料]',
   '自宅にはどのくらいの備蓄がありますか？ [お菓子]',
   '自宅にはどのくらいの備蓄がありますか？ [調理器具（ex: ガスコンロ）]',
   '自宅にはどのくらいの備蓄がありますか？ [生活用品]',
   '在宅時に大地震に襲われて、住宅が半壊しました。\n最初に、どこへ歩いて避難しますか？'],
  ['2022/11/26 4:50:11',
   '男性',
   '2',
   '1人',
   '2人',
   '1人',
   '0人',
   '1人',
   '2人',
   '耐震 & 防火工事をしている',
   '家族2日分',
   'ほぼ無し',
   '家族1日分',
   '家族3日分',
   'それ以上',
   '会社'],
  ['2022/11/26 5:07:45',
   '女性',
   '4',
   '0人',
   '0人',
   '1人',
   '0人',
   '0人',
   '0人',
   '不明',
   '家族1日分',
   '家族1日分',
   '家族2日分',
   'ほぼ無し',
   'ほぼ無し',
   '近くの避難所']]}

In [36]:
cols = jsonData['values'][0]
len_v = len(jsonData['values'])


# 通常の場合の、各備蓄物資への変化
effect_on_water = -1
effect_on_food = -1
effect_on_toilet = -1
effect_on_baby = -1
effect_on_women = -1
effect_on_elderly = -1


for i in range(1,len_v):
    v = jsonData['values'][i]
    
    '''
    ロジック：（for demo in 078kobe）
    - 【家族構成】×【どこへ歩いて避難しますか？】の2つのデータを用いる。
    - 何も問題がない場合、（完全な想定内＝従業員が会社に避難する。）全ての備蓄物が、1日分だけ減る。
        - 従業員が会社に避難しない場合、その分だけ備蓄物の減りは遅くなる。
        - 従業員が家族と共に会社に避難した場合、その分だけ備蓄物の減りは早くなる。
        - 1人分の変化は、1/3目盛り分とする。（10人程度の中小企業が対象と思えば妥当ではないだろうか。）
        （※単純化のために、最小/最大の1日の減りは0~3分目とする。つまり想定の0~3倍。）
    【家族構成】
        - 家族構成で特に、注目するのは幼児・成人女性・高齢者。なぜなら、彼/彼女らの特定の備蓄品は少ないと思われるから。
        - 子供は成人男性としてカウントする。（特に特別な物資を必要としないため。）
    【どこへ歩いて避難しますか？】
        - 会社の場合
            →（社員が独身の場合）：想定内。
            →（社員が家族と暮らしている場合）：想定してなかった人も来るということで、備蓄の過小ポイント。
        - 会社以外の場合→想定していた社員が来ないということで、備蓄の過剰ポイント。
    
    '''
    
    
    gender = v[1]
    
    
    
    #【家族構成】 幼児　（"人"が含まれているので数字だけする。）
    num_baby = int(v[3][0])
    
    #【家族構成】 子供
    num_child = int(v[4][0])
    
    #【家族構成】 成人（男性）
    num_man = int(v[5][0])
    
    #【家族構成】 成人（女性）
    num_woman = int(v[6][0])
    
    #【家族構成】 高齢者（男性、65歳以上）
    num_elder_man = int(v[7][0])
    
    #【家族構成】 高齢者（女性、65歳以上）
    num_elder_woman = int(v[8][0])
    
    #家族人数
    family_number = num_baby + num_child + num_man + num_woman + num_elder_man + num_elder_woman
    
    
    #【どこへ歩いて避難しますか？】
    answer_15 = v[-1]
    
    
    # '完全な想定内'ー＞従業員は独身で、（自宅が半壊した場合、）会社に避難する。
    if (answer_15 == '会社') & (family_number==1):
        pass
        
    # '想定外の不足'ー＞従業員は家族と共に、（自宅が半壊した場合、）会社に避難する。
    elif (answer_15 == '会社') & (family_number>1):
        number_effect = family_number-1
        # （性別・年齢に関わらず）人数の影響を受ける備蓄：
        effect_on_water -=  number_effect/3
        effect_on_food -=  number_effect/3
        effect_on_toilet -=  number_effect/3
        
        #特定の年齢/性別によって影響を受ける備蓄：
        effect_on_baby -= num_baby/3
        effect_on_women -= (num_woman + num_elder_woman)/3
        effect_on_elderly -= (num_elder_man + num_elder_woman)/3
        
    
    # '想定外の余り'ー＞従業員は（自宅が半壊した場合、）会社に避難しない。
    elif (answer_15 != '会社'):
        
        # （性別・年齢に関わらず）人数の影響を受ける備蓄：
        effect_on_water +=  1/3
        effect_on_food +=  1/3
        effect_on_toilet +=  1/3
        
        if gender == '女性':
            effect_on_women += 1/3
            

        
# 最終的な調整：　　　 （※単純化のために、最小/最大の1日の減りは0~3分目とする。つまり想定の0~3倍。）

# +（備蓄が増える現象）にならないように調整。
effect_on_water = min(0, effect_on_water)
effect_on_food = min(0, effect_on_food)
effect_on_toilet = min(0, effect_on_toilet)
effect_on_baby = min(0, effect_on_baby)
effect_on_women = min(0, effect_on_women)
effect_on_elderly = min(0, effect_on_elderly)

# -（備蓄の減り）が大きくなりすぎないように調整。
effect_on_water = max(-3, effect_on_water)
effect_on_food = max(-3, effect_on_food)
effect_on_toilet = max(-3, effect_on_toilet)
effect_on_baby = max(-3, effect_on_baby)
effect_on_women = max(-3, effect_on_women)
effect_on_elderly = max(-3, effect_on_elderly)

In [43]:
effect_on_elderly

-2.0

In [17]:
effect_on_elderly

-3

In [44]:
[1,1,1]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [69]:
for i in range(1,3):
    print(i)

1
2